///////////////////////////////////////////////////////////////////
//          THIS FILE IS FOR HANDING KIRA'S MODULE SYSTEM        //
//  DO NOT EDIT THIS FILE IF YOU DO NOT KNOW WHAT YOU ARE DOING  //
//              ANY EDIT MAY COMPLETELY BREAK KIRA               //
//              AND MAKE THE BOT UNABLE TO FUNCTION              //
///////////////////////////////////////////////////////////////////

// var kira = require('./kira.js');    // Require Kira
// const fs = require('fs');           // FS


// module.exports = {
    
//     // Load bot files
//     loadBotFiles : function() {
//         const commandFiles = fs.readdirSync('./modules').filter(file => file.endsWith('.js'));

//         // Search through files in modules
//         for (const fileName of commandFiles) {
//             // Log the filename loaded
//             console.log(`Loaded file ${fileName}`)

//             // Set the require of the file
//             const file = require(`./modules/${fileName}`);

//             // Iterate through commands in file
//             for (var cmd in file.commands) {
//                 // set a new item in the Collection
//                 // with the key as the command name and the value as the exported module
//                 kira.bot.commands.set(file["commands"][cmd].name, file["commands"][cmd]);
//             }
//         }
//     }
// }